test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -73,26 +73,37 @@ runs:
 
         echo "$FILE_MAP" > file_map.json
         echo "File map created"  
+        echo "${{ steps.changed-files.outputs.ENV_CHANGED_FILES }}"
+        cat file_map.json
 
     - name: Send to API
       shell: bash
       run: |
         # Create the payload with file map and commit details
 
-        payload=$(jq -n \
-        --slurpfile fileMap file_map.json \
-        --arg authorEmail "${{ github.event.head_commit.author.email || inputs.AUTHOR_EMAIL }}" \
-        --arg message "${{ github.event.head_commit.message || 'Automated commit'}}" \
-        '{fileMap: $fileMap[0], authorEmail: $authorEmail, message: $message}')
-        
-        # Make the API request with the file map
-        response_code=$(curl -X PUT \
-            -H "Content-Type: application/json" \
-            -H "api-key: ${{ inputs.GANYMEDE_API_TOKEN }}" \
-            -d "$payload" \
-            https://${{ inputs.GANYMEDE_SUBDOMAIN }}.ganymede.bio/v0/environment/${{ inputs.ENVIRONMENT }}/commits -w "%{http_code}" -o /dev/null)
-        
-        if [[ "$response_code" != 2* ]]; then
-            echo "Request failed with response code $response_code"
-            exit 1
-        fi
+          payload=$(jq -n \
+          --slurpfile fileMap file_map.json \
+          --arg authorEmail "${{ github.event.head_commit.author.email || inputs.AUTHOR_EMAIL }}" \
+          --arg message "${{ github.event.head_commit.message || 'Automated commit'}}" \
+          '{fileMap: $fileMap[0], authorEmail: $authorEmail, message: $message}')
+
+          echo $payload
+          
+          # Make the API request with the file map and capture both status code and response body
+          response_file=$(mktemp)
+          response_code=$(curl -X PUT \
+              -H "Content-Type: application/json" \
+              -H "api-key: ${{ inputs.GANYMEDE_API_TOKEN }}" \
+              -d "$payload" \
+              https://${{ inputs.GANYMEDE_SUBDOMAIN }}.ganymede.bio/v0/environment/${{ inputs.ENVIRONMENT }}/commits \
+              -w "%{http_code}" -o "$response_file")
+          
+          if [[ "$response_code" != 2* ]]; then
+              echo "Request failed with response code $response_code"
+              echo "Error response body:"
+              cat "$response_file"
+              rm "$response_file"
+              exit 1
+          fi
+          
+          rm "$response_file"
